export const orderColumns = [
    {
      title: 'Order ID',
      dataIndex: 'orderId',
      key: 'orderId',
    },
    {
      title: 'Date',
      dataIndex: 'date',
      key: 'date',
    },
    {
      title: 'Customer Name',
      dataIndex: 'customerName',
      key: 'customerName',
    },
    {
      title: 'Address',
      dataIndex: 'address',
      key: 'address',
    },
    {
      title: 'Amount',
      dataIndex: 'amount',
      key: 'amount',
      render: amount => `₹ ${amount}`,
    },
  ];
  
  export const orderData = [
    {
      key: '1',
      orderId: '001',
      date: '2024-04-30',
      customerName: 'Suresh',
      address: '123 Street, Bangalore',
      amount: 260,
      status: 'New Order',
    },
    {
      key: '2',
      orderId: '002',
      date: '2024-04-28',
      customerName: 'Radhika',
      address: '#45 HBR Layout, Bangalore',
      amount: 2000,
      status: 'On Delivery',
    },
    {
      key: '2',
      orderId: '023',
      date: '2024-04-25',
      customerName: 'Kamlesh',
      address: '123 Street, City',
      amount: 100,
      status: 'New Order',
    },
    {
      key: '1',
      orderId: '001',
      date: '2024-04-30',
      customerName: 'John Doe',
      address: '123 Street, City',
      amount: 100,
      status: 'New Order',
    },
    {
      key: '1',
      orderId: '001',
      date: '2024-04-30',
      customerName: 'John Doe',
      address: '123 Street, City',
      amount: 100,
      status: 'New Order',
    },
    {
      key: '1',
      orderId: '001',
      date: '2024-04-30',
      customerName: 'John Doe',
      address: '123 Street, City',
      amount: 100,
      status: 'New Order',
    },
    {
      key: '1',
      orderId: '001',
      date: '2024-04-30',
      customerName: 'John Doe',
      address: '123 Street, City',
      amount: 100,
      status: 'New Order',
    },
    {
      key: '1',
      orderId: '001',
      date: '2024-04-30',
      customerName: 'John Doe',
      address: '123 Street, City',
      amount: 100,
      status: 'New Order',
    },
    {
      key: '1',
      orderId: '001',
      date: '2024-04-30',
      customerName: 'John Doe',
      address: '123 Street, City',
      amount: 100,
      status: 'New Order',
    },
    {
      key: '1',
      orderId: '001',
      date: '2024-04-30',
      customerName: 'John Doe',
      address: '123 Street, City',
      amount: 100,
      status: 'New Order',
    },
    {
      key: '1',
      orderId: '001',
      date: '2024-04-30',
      customerName: 'John Doe',
      address: '123 Street, City',
      amount: 100,
      status: 'New Order',
    },
    // Add more dummy data here...
  ];
  