export const reviewData = [
    {
      key: '1',
      avatar: 'https://images.pexels.com/photos/1674752/pexels-photo-1674752.jpeg?auto=compress&cs=tinysrgb&w=600',
      name: 'John Doe',
      reviewId: '#REV001',
      date: '2022-05-19',
      time: '10:00 AM',
      review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      rating: 4,
      totalSpent: '$100',
    },
    {
      key: '1',
      avatar: 'https://images.pexels.com/photos/1674752/pexels-photo-1674752.jpeg?auto=compress&cs=tinysrgb&w=600',
      name: 'John Doe',
      reviewId: '#REV001',
      date: '2022-05-19',
      time: '10:00 AM',
      review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      rating: 3,
      totalSpent: '$100',
    },
    {
      key: '1',
      avatar: 'https://images.pexels.com/photos/1674752/pexels-photo-1674752.jpeg?auto=compress&cs=tinysrgb&w=600',
      name: 'John Doe',
      reviewId: '#REV001',
      date: '2022-05-19',
      time: '10:00 AM',
      review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      rating: 2,
      totalSpent: '$100',
    },
    {
      key: '1',
      avatar: 'https://images.pexels.com/photos/1674752/pexels-photo-1674752.jpeg?auto=compress&cs=tinysrgb&w=600',
      name: 'John Doe',
      reviewId: '#REV001',
      date: '2022-05-19',
      time: '10:00 AM',
      review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      rating: 4,
      totalSpent: '$100',
    },
    {
      key: '1',
      avatar: 'https://images.pexels.com/photos/1674752/pexels-photo-1674752.jpeg?auto=compress&cs=tinysrgb&w=600',
      name: 'John Doe',
      reviewId: '#REV001',
      date: '2022-05-19',
      time: '10:00 AM',
      review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      rating: 5,
      totalSpent: '$100',
    },
    {
      key: '1',
      avatar: 'https://images.pexels.com/photos/1674752/pexels-photo-1674752.jpeg?auto=compress&cs=tinysrgb&w=600',
      name: 'John Doe',
      reviewId: '#REV001',
      date: '2022-05-19',
      time: '10:00 AM',
      review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      rating: 4,
      totalSpent: '$100',
    },
    {
      key: '1',
      avatar: 'https://images.pexels.com/photos/1674752/pexels-photo-1674752.jpeg?auto=compress&cs=tinysrgb&w=600',
      name: 'John Doe',
      reviewId: '#REV001',
      date: '2022-05-19',
      time: '10:00 AM',
      review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      rating: 4,
      totalSpent: '$100',
    },
    // Add more review data as needed
  ];
  