
export const userData = [
    {
      orderId: '1001',
      date: '2024-05-24',
      customerName: 'John Doe',
      location: 'Lucknow, India',
      totalSpent: 500,
      lastOrderPrice: 100,
      rating: 4,
    },
    {
      orderId: '1002',
      date: '2024-05-23',
      customerName: 'Jane Smith',
      location: 'Mumbai, India',
      totalSpent: 750,
      lastOrderPrice: 150,
      rating: 5,
    },
    {
        orderId: '1001',
        date: '2024-05-24',
        customerName: 'John Doe',
        location: 'Lucknow, India',
        totalSpent: 500,
        lastOrderPrice: 100,
        rating: 4,
      },
      {
        orderId: '1001',
        date: '2024-05-24',
        customerName: 'John Doe',
        location: 'Lucknow, India',
        totalSpent: 500,
        lastOrderPrice: 100,
        rating: 4,
      },
      {
        orderId: '1001',
        date: '2024-05-24',
        customerName: 'John Doe',
        location: 'Lucknow, India',
        totalSpent: 500,
        lastOrderPrice: 100,
        rating: 4,
      },
      {
        orderId: '1001',
        date: '2024-05-24',
        customerName: 'John Doe',
        location: 'Lucknow, India',
        totalSpent: 500,
        lastOrderPrice: 100,
        rating: 4,
      },
      {
        orderId: '1001',
        date: '2024-05-24',
        customerName: 'John Doe',
        location: 'Lucknow, India',
        totalSpent: 500,
        lastOrderPrice: 100,
        rating: 4,
      },
      {
        orderId: '1001',
        date: '2024-05-24',
        customerName: 'John Doe',
        location: 'Lucknow, India',
        totalSpent: 500,
        lastOrderPrice: 100,
        rating: 4,
      },
      {
        orderId: '1001',
        date: '2024-05-24',
        customerName: 'John Doe',
        location: 'Lucknow, India',
        totalSpent: 500,
        lastOrderPrice: 100,
        rating: 4,
      },
      {
        orderId: '1001',
        date: '2024-05-24',
        customerName: 'John Doe',
        location: 'Lucknow, India',
        totalSpent: 500,
        lastOrderPrice: 100,
        rating: 4,
      },
      {
        orderId: '1001',
        date: '2024-05-24',
        customerName: 'John Doe',
        location: 'Lucknow, India',
        totalSpent: 500,
        lastOrderPrice: 100,
        rating: 4,
      },
      {
        orderId: '1001',
        date: '2024-05-24',
        customerName: 'John Doe',
        location: 'Lucknow, India',
        totalSpent: 500,
        lastOrderPrice: 100,
        rating: 4,
      },
      {
        orderId: '1001',
        date: '2024-05-24',
        customerName: 'John Doe',
        location: 'Lucknow, India',
        totalSpent: 500,
        lastOrderPrice: 100,
        rating: 4,
      },
      {
        orderId: '1001',
        date: '2024-05-24',
        customerName: 'John Doe',
        location: 'Lucknow, India',
        totalSpent: 500,
        lastOrderPrice: 100,
        rating: 4,
      },
      {
        orderId: '1001',
        date: '2024-05-24',
        customerName: 'John Doe',
        location: 'Lucknow, India',
        totalSpent: 500,
        lastOrderPrice: 100,
        rating: 4,
      },
];